version: '3.9'

volumes:
  geo-db-data:

services:
  db:
    image: kartoza/postgis:14-3.1
    volumes:
      - geo-db-data:/var/lib/postgresql
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=catasto
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - ALLOW_IP_RANGE=0.0.0.0/0
      - FORCE_SSL=TRUE
    restart: on-failure
    healthcheck:
      test: "pg_isready -d gis"
