"""Added ctcn.cuutilit

Revision ID: 3241a81a8849
Revises: 2dd333f65ddc
Create Date: 2022-06-07 16:58:37.740561

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "3241a81a8849"
down_revision = "2dd333f65ddc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cuutilit",
        sa.Column("codice", sa.String(length=4), nullable=False),
        sa.Column("sezione", sa.String(length=1), nullable=False),
        sa.Column("immobile", sa.BigInteger(), nullable=False),
        sa.Column("tipo_imm", sa.String(length=1), nullable=False),
        sa.Column("progressiv", sa.Integer(), nullable=False),
        sa.Column("sez_urbana", sa.String(length=3), nullable=True),
        sa.Column("foglio", sa.String(length=4), nullable=True),
        sa.Column("numero", sa.String(length=5), nullable=True),
        sa.Column("denominato", sa.Integer(), nullable=True),
        sa.Column("subalterno", sa.String(length=4), nullable=True),
        schema="ctcn",
    )
    op.create_index(
        "cuutilit_idx1",
        "cuutilit",
        ["codice", "sezione", "immobile", "tipo_imm", "progressiv"],
        schema="ctcn",
        postgresql_using="btree",
    )


def downgrade() -> None:
    op.drop_index(
        "cuutilit_idx1",
        table_name="cuutilit",
        schema="ctcn",
        postgresql_using="btree",
    )
    op.drop_table("cuutilit", schema="ctcn")
